language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
sudo: required

solution: vikebot.sln

script:
- dotnet restore
- dotnet publish
- dotnet test ./vikebot.Test/vikebot.Test.csproj
- nupkg_suffix="-ci$TRAVIS_BUILD_NUMBER"
- dotnet pack vikebot/vikebot.csproj --configuration Release --version-suffix $nupkg_suffix
- cd vikebot/bin/Release/
- ls -l
- nuget
- nuget list vikebot -allversions -prerelease
