language: csharp
mono: none
dotnet: 1.0.1
solution: vikebot.sln
dist: trusty
sudo: required
script:
- dotnet restore
- dotnet publish
- dotnet test ./vikebot.Test/vikebot.Test.csproj
- cd vikebot
- nupkg_suffix="-ci$TRAVIS_BUILD_NUMBER"
- echo $nupkg_suffix
- dotnet pack vikebot.csproj --configuration Release --version-suffix $nupkg_suffix
- cd bin/Release/
- ls -l
